#if !canImport(ObjectiveC)
import XCTest

extension CodableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodableTests = [
        ("testCodable", testCodable),
    ]
}

extension OtherTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OtherTests = [
        ("testDoubleMake", testDoubleMake),
        ("testFloatMake", testFloatMake),
    ]
}

extension PerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PerformanceTests = [
        ("testPerformance_arc4random", testPerformance_arc4random),
        ("testPerformance_arc4random_single", testPerformance_arc4random_single),
        ("testPerformance_arc4random_uniform", testPerformance_arc4random_uniform),
        ("testPerformance_xorshift", testPerformance_xorshift),
        ("testPerformance_xorshift_normal_accelerate_double", testPerformance_xorshift_normal_accelerate_double),
        ("testPerformance_xorshift_normal_accelerate_float", testPerformance_xorshift_normal_accelerate_float),
        ("testPerformance_xorshift_normal_no_accelerate_double", testPerformance_xorshift_normal_no_accelerate_double),
        ("testPerformance_xorshift_normal_no_accelerate_float", testPerformance_xorshift_normal_no_accelerate_float),
        ("testPerformance_xorshift_single", testPerformance_xorshift_single),
        ("testPerformance_xorshift_single64", testPerformance_xorshift_single64),
        ("testPerformance_xorshift_uniform_double", testPerformance_xorshift_uniform_double),
        ("testPerformance_xorshift_uniform_float", testPerformance_xorshift_uniform_float),
    ]
}

extension XorshiftGeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XorshiftGeneratorTests = [
        ("testCompatibilityWithStdlib", testCompatibilityWithStdlib),
        ("testCoW", testCoW),
        ("testInnerState", testInnerState),
    ]
}

extension XorshiftTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XorshiftTests = [
        ("testXorshift", testXorshift),
        ("testXorshift_normal_double", testXorshift_normal_double),
        ("testXorshift_normal_float", testXorshift_normal_float),
        ("testXorshift_normal_no_accelerate_double", testXorshift_normal_no_accelerate_double),
        ("testXorshift_normal_no_accelerate_float", testXorshift_normal_no_accelerate_float),
        ("testXorshift_uniform_double", testXorshift_uniform_double),
        ("testXorshift_uniform_float", testXorshift_uniform_float),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CodableTests.__allTests__CodableTests),
        testCase(OtherTests.__allTests__OtherTests),
        testCase(PerformanceTests.__allTests__PerformanceTests),
        testCase(XorshiftGeneratorTests.__allTests__XorshiftGeneratorTests),
        testCase(XorshiftTests.__allTests__XorshiftTests),
    ]
}
#endif
