#if !canImport(ObjectiveC)
import XCTest

extension OtherTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OtherTests = [
        ("testFloatMake", testFloatMake),
        ("testDoubleMake", testDoubleMake),
    ]
}

extension XorshiftGeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XorshiftGeneratorTests = [
        ("testCoW", testCoW),
        ("testInnerState", testInnerState),
    ]
}

extension XorshiftTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XorshiftTests = [
        ("testXorshift", testXorshift),
        ("testXorshift_uniform_float", testXorshift_uniform_float),
        ("testXorshift_uniform_double", testXorshift_uniform_double),
        ("testXorshift_normal_float", testXorshift_normal_float),
        ("testXorshift_normal_double", testXorshift_normal_double),
        ("testXorshift_normal_no_accelerate_float", testXorshift_normal_no_accelerate_float),
        ("testXorshift_normal_no_accelerate_double", testXorshift_normal_no_accelerate_double),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OtherTests.__allTests__OtherTests),
        testCase(XorshiftGeneratorTests.__allTests__XorshiftGeneratorTests),
        testCase(XorshiftTests.__allTests__XorshiftTests),
    ]
}
#endif
